allow-lan: true
external-controller: :9090
log-level: info
mode: Rule
port: 7890
proxies:
- cipher: chacha20-ietf
  name: usalainap01.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 35916
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: usalainap01.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: usgia666.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 49092
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: usgia666.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: lausapple.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 19611
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: lausapple.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: usaseattlespartan.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 48826
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: usaseattlespartan.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: usalapdx.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 20355
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: usalapdx.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: usalasvegas.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 18918
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: usalasvegas.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: usa-central-dallas.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 16316
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: usa-central-dallas.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: usa-la-20350.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 20350
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: usa-la-20350.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: usala15081.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 15081
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: usala15081.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: usalaxdc02.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 31202
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: usalaxdc02.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: usamiju-33198.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 33198
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: usamiju-33198.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: westusla.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 35181
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: westusla.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: sanjose-gt-30168.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 30168
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: sanjose-gt-30168.665616.xyz
  type: ssr
proxy-groups:
- interval: 900
  name: US
  proxies:
  - usalainap01.servernode.network
  - usgia666.servernode.network
  - lausapple.servernode.network
  - usaseattlespartan.servernode.network
  - usalapdx.665616.xyz
  - usalasvegas.665616.xyz
  - usa-central-dallas.665616.xyz
  - usa-la-20350.665616.xyz
  - usala15081.665616.xyz
  - usalaxdc02.servernode.network
  - usamiju-33198.servernode.network
  - westusla.665616.xyz
  - sanjose-gt-30168.665616.xyz
  type: url-test
  url: http://www.gstatic.com/generate_204
- name: Auto
  type: select
  proxies:
  - US
socks-port: 7891
