allow-lan: true
external-controller: :9090
log-level: info
mode: Rule
port: 7890
proxies:
- cipher: chacha20-ietf
  name: usalainap01.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 35916
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: usalainap01.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: usgia666.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 49092
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: usgia666.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: lausapple.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 19611
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: lausapple.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: usaseattlespartan.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 48826
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: usaseattlespartan.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: usalapdx.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 20355
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: usalapdx.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: usalasvegas.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 18918
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: usalasvegas.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: usa-central-dallas.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 16316
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: usa-central-dallas.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: usa-la-20350.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 20350
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: usa-la-20350.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: usala15081.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 15081
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: usala15081.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: usalaxdc02.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 31202
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: usalaxdc02.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: us-36696-cluster.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 36696
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: us-36696-cluster.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: usamiju-33198.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 33198
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: usamiju-33198.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: westusla.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 35181
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: westusla.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: sanjose-gt-30168.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 30168
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: sanjose-gt-30168.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: jp-02.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 29162
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: jp-02.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: jpsushi.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 35836
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: jpsushi.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: jp-jinju-18619.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 18619
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: jp-jinju-18619.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: jpbgp-20351.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 20351
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: jpbgp-20351.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: jpgj01.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 38392
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: jpgj01.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: jplite-33161.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 33161
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: jplite-33161.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: osaka46981.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 46981
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: osaka46981.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: jp03-39367.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 39367
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: jp03-39367.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: jpstrawberry.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 36098
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: jpstrawberry.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: korea-12279.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 12279
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: korea-12279.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: ovb-21802.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 21802
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: ovb-21802.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: uslamc03.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 21196
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: uslamc03.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: hkhktzz.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 48136
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: hkhktzz.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: hkhktzz2.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 48138
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: hkhktzz2.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: hkhkg26853.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 26853
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: hkhkg26853.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: hkma20359.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 20359
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: hkma20359.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: turkey-40216.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 40216
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: turkey-40216.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: inap-2-39116.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 39116
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: inap-2-39116.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: relay21801.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 21801
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: relay21801.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: hkwtt.any.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 39166
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: hkwtt.any.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: usa-sanjose.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 33986
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: usa-sanjose.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: usashanzha49091.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 49091
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: usashanzha49091.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: vn-hanoi-50082.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 50082
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: vn-hanoi-50082.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: hkanyhgc.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 38662
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: hkanyhgc.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: hkhj-01.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 24301
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: hkhj-01.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: relay-data-19136.665616.xyz
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 19136
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: relay-data-19136.665616.xyz
  type: ssr
- cipher: chacha20-ietf
  name: tunnelrelay26101.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 26101
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: tunnelrelay26101.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: twhinet01.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 35968
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: twhinet01.servernode.network
  type: ssr
- cipher: chacha20-ietf
  name: hkgj39268.servernode.network
  obfs: plain
  obfs-param: ea884c65371.cloudfront.com
  password: GdCaGo
  port: 39268
  protocol: auth_aes128_md5
  protocol-param: 65371:5QKcK7
  server: hkgj39268.servernode.network
  type: ssr
proxy-groups:
- interval: 900
  name: US
  proxies:
  - usalainap01.servernode.network
  - usgia666.servernode.network
  - lausapple.servernode.network
  - usaseattlespartan.servernode.network
  - usalapdx.665616.xyz
  - usalasvegas.665616.xyz
  - usa-central-dallas.665616.xyz
  - usa-la-20350.665616.xyz
  - usala15081.665616.xyz
  - usalaxdc02.servernode.network
  - us-36696-cluster.665616.xyz
  - usamiju-33198.servernode.network
  - westusla.665616.xyz
  - sanjose-gt-30168.665616.xyz
  type: url-test
  url: http://www.gstatic.com/generate_204
- interval: 900
  name: JP
  proxies:
  - jp-02.servernode.network
  - jpsushi.servernode.network
  - jp-jinju-18619.servernode.network
  - jpbgp-20351.servernode.network
  - jpgj01.servernode.network
  - jplite-33161.665616.xyz
  - osaka46981.665616.xyz
  - jp03-39367.665616.xyz
  - jpstrawberry.665616.xyz
  - korea-12279.665616.xyz
  type: url-test
  url: http://www.gstatic.com/generate_204
- interval: 900
  name: HK
  proxies:
  - ovb-21802.servernode.network
  - uslamc03.servernode.network
  - hkhktzz.servernode.network
  - hkhktzz2.servernode.network
  - hkhkg26853.665616.xyz
  - hkma20359.665616.xyz
  - turkey-40216.665616.xyz
  - inap-2-39116.665616.xyz
  - relay21801.servernode.network
  - hkwtt.any.servernode.network
  - usa-sanjose.665616.xyz
  - usashanzha49091.665616.xyz
  - vn-hanoi-50082.665616.xyz
  - hkanyhgc.servernode.network
  - hkhj-01.servernode.network
  - relay-data-19136.665616.xyz
  - tunnelrelay26101.servernode.network
  - twhinet01.servernode.network
  - hkgj39268.servernode.network
  type: url-test
  url: http://www.gstatic.com/generate_204
- name: Auto
  proxies:
  - US
  - JP
  - HK
  type: select
socks-port: 7891
